site_name: Tina Framework
theme:
  name: material
  favicon: 'assets/icon.png'
  logo: 'assets/docs_icon.png'
  palette:
    scheme: slate
    primary: deep purple
    accent: purple
  features:
  - announce.dismiss
  - content.code.annotate
  - content.tabs.link
  - content.tooltips
  # - header.autohide
  - navigation.expand
  - navigation.indexes
  # - navigation.instant
  # - navigation.prune
  - navigation.sections
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
  - navigation.tracking
  - search.highlight
  - search.share
  - search.suggest
  - toc.follow
  - toc.integrate

extra_css:
  - stylesheets/extra.css

repo_url: https://github.com/AetherInteractiveLtd/Tina
repo_name: Aether/Tina

plugins:
  - tags
  - blog:
      enabled: true
      post_date_format: full
      post_url_date_format: yyyy
      post_url_format: '{date}/{slug}'
      authors: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - def_list
  - tables
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
- Home: 'index.md'

- API:
  - 'Getting Started': 'api/api_docs.md'
  - 'API Detail': 'api/coverage.md'
  - 'Tina': 'api/tina.md'
  - 'Condition': 'api/condition.md'
  - 'Process': 'api/process.md'
  - 'EventEmitter': 'api/event_emitter.md'
  - 'EventListener': 'api/event_listener.md'
  - Extras:
    - 'api/types/manifest.md'

- Tina Guide:
  - 'The Philosophy': 'intro/tina/philosophy.md'
  - 'Getting Started': 'intro/tina/start.md'
  - 'Main Features': 'intro/tina/core.md'

  - Lib:
    - 'Events': 'intro/tina/libraries/events.md'
    - 'Conditions': 'intro/tina/libraries/conditions.md'
    - 'Processes': 'intro/tina/libraries/processes.md'

  - 'Networking': 'intro/tina/libraries/net/net.md'

  - 'Entity Component System': 'intro/tina/ecs.md'

- Blog: 'blog/index.md'