site_name: Aether Developers
theme: readthedocs

nav:
- Home: 'index.md'

- Tina Guide:
  - 'The Philosophy': 'intro/tina/philosophy.md'
  - 'Getting Started': 'intro/tina/start.md'
  - 'Main Features': 'intro/tina/core.md'

  - Lib:
    - 'Events': 'intro/tina/libraries/events.md'
    - 'Conditions': 'intro/tina/libraries/conditions.md'
    - 'Processes': 'intro/tina/libraries/processes.md'

  - 'Networking': 'intro/tina/libraries/net/net.md'

  - 'Entity Component System': 'intro/tina/ecs.md'